rest:
  handler: src/rest/index.handle
  environment:
    ENTITIES_TABLE_NAME: ${opt:stage}-${self:service}-entities
  iamRoleStatementsName: ${self:provider.stackName}-rest-role
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt [EntitiesTable, Arn]
  events:
    - http:
        path: "{proxy+}"
        method: any
        authorizer:
          name: PrivateAuthorizer
          type: COGNITO_USER_POOLS
          arn: ${cf:${self:custom.infraStack}.poolArn}
          scopes:
            - aws.cognito.signin.user.admin

listener:
  handler: src/listener/index.handle
  events:
    - stream:
        type: kinesis
        arn: ${cf:${self:custom.infraStack}.streamArn}
        batchSize: 100
        startingPosition: TRIM_HORIZON

trigger:
  handler: src/trigger/index.handle
  events:
    - stream:
        type: dynamodb
        arn:
          Fn::GetAtt: [EntitiesTable, StreamArn]
        batchSize: 100
        startingPosition: TRIM_HORIZON
