name: Catalog pipeline

on:
    push:
        branches: [main]
        paths:
            - "catalog/**"
            - ".github/workflows/catalog-pipeline.yml"

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl
            default: true

      - name: Build Rust Lambda
        working-directory: ./catalog
        run: |
            rustup target add x86_64-unknown-linux-musl
            cargo build --release --target x86_64-unknown-linux-musl --bin lambda
            cp target/x86_64-unknown-linux-musl/release/lambda bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init & deploy
        working-directory: ./catalog/cloud
        run: |
            terraform init
            terraform apply -auto-approve